### ISSUE TITLE
TransformBlock\TransformFinalBlock does not work correctly or is not supported

### ISSUE THREAD

**Issue by AlexanderShanin** [onix-labs/onixlabs-dotnet#82]
```
byte[] inputBuffer = Encoding.UTF8.GetBytes("abc");
//OK 3A985DA74FE225B2045C172D6BD390BD855F086E3E9D525B46BFE24511431532
Console.WriteLine(BitConverter.ToString(/*SHA256.Create()*/new Sha3Hash256().ComputeHash(inputBuffer)).Replace("-", ""));
using (HashAlgorithm hashAlgorithm = /*SHA256.Create()*/new Sha3Hash256()) {
    //hashAlgorithm.Initialize();
    hashAlgorithm.TransformBlock(inputBuffer, 0, inputBuffer.Length, null, 0);
    hashAlgorithm.TransformFinalBlock(new byte[0], 0, 0);
    //ERR A7FFC6F8BF1ED76651C14756A061D662F580FF4DE43B49FA82D80A4B80F8434A
    Console.WriteLine(BitConverter.ToString(hashAlgorithm.Hash).Replace("-", ""));
}
```
Sha3.HashCore starts with a call to Initialize. As far as I understand, HashCore should not constantly reset the state if the implementation involves multiple calls to HashAlgorithm.TransformBlock. Or is there perhaps another way to pass data in portions?

**Comment by MrMatthewLayton** [comment]
@AlexanderShanin Thanks for raising this, and apologies for the three week delayed response. I will investigate this ASAP.

**Comment by AlexanderShanin** [comment]
Thank you, I will wait for your answer

**Comment by MrMatthewLayton** [comment]
@AlexanderShanin Thank you again for identifying this issue, which should now be fixed in this PR: https://github.com/onix-labs/onixlabs-dotnet/pull/85

Tests are passing, so I'll get this merged and released today.
